
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: subscription_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d subscription_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=subscription_db
      - DB_USER=user
      - DB_PASSWORD=password
      - APP_PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["go", "run", "./cmd/server/main.go"]

volumes:
  postgres_data: